[package]
name = "car_fib"
version = "0.1.0"
authors = ["Himenon <6715229+Himenon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
